version: "3"
services: 
  phpfpm:
    build: './php'
    networks: 
      - belakang
    depends_on: 
      - db
    ports: 
      - 9000:9000
    volumes: 
      - ./html:/usr/share/nginx/html
  db:
    image: mysql:5.7
    #command: 'mysql default-authentication-plugin=mysql_native_password'
    networks: 
      - belakang
    ports: 
      - 3306:3306
    environment: 
      - MYSQL_ROOT_PASSWORD=rootpassword
  nginx:
    image: nginx
    networks: 
      - depan
      - belakang
    ports: 
      - 80:80
    volumes: 
      - ./html:/usr/share/nginx/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on: 
      - db
      - phpfpm
networks: 
  depan:
  belakang: